services:
  gateway:
    image: bwdesigngroup/ignition-docker:latest
    hostname: blob
    labels:
      traefik.enable: "true"
      traefik.hostname: blob
    volumes:
      - ./ignition-data:/workdir
      - ./backups/gateway.gwbk:/restore.gwbk
    environment:
      SYMLINK_GITIGNORE: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: blob
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: blob.localtest.me
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy
    
  database:
    image: bwdesigngroup/mssql-docker
    hostname: mssql
    ports:
      - 8443:1433
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    # Uncomment the following line to enable backups
    # Put all db backups in ./sql-backups folder
    #  - ./sql-backups:/backups
    labels:
      traefik.enable: "true"
      traefik.hostname: blob-database
    networks:
      - default
      - proxy


networks:
  default:
  proxy:
    external: true
    name: proxy